name: "My composite action"
description: "Checks out the repository and does something"
runs:
  using: "composite"
  steps: 
  - run |
      echo "Executing composite run steps action"
    shell: bash
