name: Test artifacts job
on:
  push:
    paths:
      - '.github/workflows/artifacts.yaml'

jobs:
  artifactJob:
    name: Upload artifacts
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          mkdir --version
          mkdir -v test
          sudo mkdir –pv bladebug/blainfrastructure
          uuidgen > debug/infrastructure/file.txt
          mkdir –p ./debug/scripts
          uuidgen > debug/scripts/file.txt
          mkdir –p ./debug/function_packages/fa1
          uuidgen > debug/function_packages/fa1/file.txt
          ls
      - name: publish artifact
        uses: actions/upload-artifact@v2
        with:
          path: |
            debug/infrastructure
            debug/scripts
            debug/function_packages
          name: files-${{github.run_number}}
          
