name: Test check-outcome
on:
  push:
    paths:
      - '.github/workflows/check-outcome.yaml'

jobs:
  mainJob:
    name: Test
    runs-on: ubuntu-latest
    
    steps:      
      - name: Step A
        id: seedBuild
        run: |
          echo "failing on purpose"
          exit 1

      - name: Step B
        if: ${{ always() }}
        id: allSteps
        run: |
          echo "test"

      - name: Debug Step Failure
        run: |
          echo "******** Job Logs from ********"
        if: "${{ always() && (steps.seedBuild.outcome == 'failure' || steps.allSteps.outcome == 'failure') }}"
