name: GitHub script action
on:
  push:
    paths:
    - '.github/workflows/github-script.yaml'

jobs:
  getReleaseJob:
    name: Get latest release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v4
      id: set-result
      with:
        script: |
          const { upload_url } = await github.issues.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: '1'
          })
          return upload_url
        result-encoding: string
    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}"
