name: Test linux job
on:
  push:
    paths:
      - '.github/workflows/linux.yaml'

jobs:
  downloadJob:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${GITHUB_REF#refs/heads/}"
          echo "Printing github context"
          echo "${{ toJson(github) }}"
          uuidgen
          pwd
          ls
      - run: |
          # print commands
          set -x
          git config --list --show-origin
          git config --global --get user.name
          git config --global --get user.email
      - id: set_var
        run: |
          echo "{\"project\":\"foo\",\"config\":\"Debug\"}" | tee package.json
          content=`cat package.json`
          echo "::set-output name=packageJson::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).project}}"
