name: Test linux job
on:
  push:
    paths:
      - '.github/workflows/linux.yaml'

jobs:
  downloadJob:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: set_var
        run: |
          echo "{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" | tee package.json
          content=`cat package.json`
          echo "::set-output name=packageJson::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).project}}"
