name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Test'     
        required: false
        
jobs:
  firstJob:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Test"
        echo "${{ toJson(github) }}"
