on:
  pull_request:
    types: [opened, closed, reopened]

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}

jobs:
  prJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_PR_NUMBER"
          echo "$GITHUB_CONTEXT"
          echo "${{ toJson(github.event) }}"
          echo "${{ github.event.action }}"
      - run: |
          echo "${{toJson(github.event.pull_request.number)}}"
          githubEvent="${{toJson(github.event.action)}}"
          
          githubEvent="${githubEvent//'%'/'%25'}"
          githubEvent="${githubEvent//$'\n'/'%0A'}"
          githubEvent="${githubEvent//$'\r'/'%0D'}" 
          echo "$githubEvent"
      - name: Get branch name
        shell: bash
        run: echo "::set-output name=branch::${${{github.ref}}#refs/heads/}"
        id: get_branch
      - run: echo "${{steps.get_branch.outputs.branch}}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.ref }}
      - name: print diff
        run: |
          git diff origin/main..HEAD > branches-diff
          echo "branches-diff = "
          cat branches-diff
        
