on:
  pull_request:
    types: [opened, closed, reopened]
        
jobs:
  downloadJob:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{fromJson(github.event)}}"
