on:
  pull_request:
    types: [opened, closed, reopened]
        
jobs:
  prJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "{{fromJson(github.event)}}"
          echo Test
