name: Download file
on:
  push

jobs:
  downloadJob:
    name: Download file
    runs-on: windows-2019
    steps:
      - id: download_msi
        run: |
          Write-Output "Test"
          echo "Test 2"
          $msiUrl = "https://mtgarena.downloads.wizards.com/Live/Windows32/versions/2133.772345/MTGAInstaller_0.1.2133.772345.msi"
          $fileName = (([uri]$msiUrl).Segments)[-1]
          $msiFilePath = "$Env:GITHUB_WORKSPACE\..\$fileName"
          Write-Output $msiFilePath
          echo "::set-output name=msiFilePath::$msiFilePath"
      - run: |
          Write-Output "${{ steps.download_msi.outputs.msiFilePath }}"

