name: Test summary workflow
on:
  push:
    paths:
      - '.github/workflows/summary.yaml'

jobs:
  single-job:
    name: Set summary job
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
        run: echo '### Hello world! ' >> $GITHUB_STEP_SUMMARY
      - name: Adding more markdown
        run: echo '## Moar! ' >> $GITHUB_STEP_SUMMARY
