name: Use composite action
on:
  push:
    paths:
    - '.github/workflows/use-composite-action.yaml'
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/composite-run-steps-action
