name: windows-latest workflow
on:
  push:
    paths:
      - '.github/workflows/windows-latest.yaml'

jobs:
  job:
    name: Windows-Latest
    runs-on: windows-2019
    steps:      
      - name: Do some stuff
        run: |
          $Env:Path.Split(';')
