name: Try some PowerShell stuff
on:
  push:
    paths:
      - '.github/workflows/windows-powershell.yaml'

jobs:
  buildjob:
    name: Test job
    runs-on: windows-latest
    steps:
      - run: echo ${{github.workspace}}
      - name: Test some commands
        id: test
        run: |
          echo "bla" >> bla.txt
          cat bla.txt
          $msiFilePath = "C:\test.msi"
          echo $Env:GITHUB_OUTPUT
          echo "{{msiFilePath}}={{$msiFilePath}}" >> $Env:GITHUB_OUTPUT
          cat $Env:GITHUB_OUTPUT
      - run: echo ${{ steps.test.outputs.msiFilePath }}
