name: Check latest MTGA version on commit
on:
  push:
    paths:
      - '.github/workflows/windows.yaml'

jobs:
  buildjob:
    name: Get latest MTGA version
    runs-on: windows-2019
    steps:      
      - name: Commit proto
        run: |
          Copy-Item "${{steps.extract-proto.outputs.protoPath}}" -Destination "messages.proto"
          # git config --global user.name 'riQQ'
          # git config --global user.email 'riQQ@users.noreply.github.com'
          git add messages.proto
          git diff-index --quiet HEAD
          if( $? )
          {
            echo "No changes to commit and push"
            exit
          }
                    
          git commit -m "Update proto"
          git push
        shell: |
          pwsh -noninteractive -ExecutionPolicy Unrestricted -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ echo ""FAILED: $_""; echo ""$_.ScriptStackTrace""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
          
