on:
  workflow_run:
    workflows: ["Manual workflow"]
    types: [completed]
    
jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context        
      run: |
        echo "${{ toJson(github.event) }}"
