name: default

on:
  push:
    branches:
    - '.github/workflows/yaml-identation.yaml'
    
jobs:
  testJob:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Test"
